### PR TITLE
Redefined function call with proper parameters 

### PR DESCRIPTION
**Pull request by Kappuccino111**
The following error in `make` has been fixed @tillkamppeter @michaelrsweet 

image

### CODE REVIEW

**Comment by tillkamppeter** [comment]
Have you tested building with both libcups2 and libcups3?

**Comment by Kappuccino111** [comment]
@tillkamppeter also updated install.md

**Comment by tillkamppeter** [comment]
Note that the CUPS master branch is NOT libcups3, the CUPS master branch is CUPS 2.5.x.

To compile with libcups3, install libcups3 (does not overwrite anything of installed CUPS 2.5.x, then, in libcupsfilters and libppd do
```
make distclean
./configure
make
sudo make install
```
Check the output of `./configure` to see whether it really selected libcups3 and not libcups2.

**Comment by Kappuccino111** [comment]
Compiled with libcups 3 .... works perfectly @tillkamppeter 

image

**Pull request merged**
